# ── wykonane działania (klucz → polska etykieta) ───────────────────────────────
# Kolejność listy wyznacza kolejność w pytaniu wielokrotnego wyboru (questionary).
ACTIONS = [
    # żywienie
    "feeding_syrup",
    "feeding_candy",
    "feeding_pollen",
    "feeding_water",
    # gospodarka plastrem
    "comb_added_drawn",
    "comb_added_foundation",
    "comb_removed_old",
    "comb_removed_drone",
    "uncapping",
    # przestrzeń i gospodarka
    "super_added",
    "super_removed",
    "division_board_moved",
    "hive_expanded",
    # miodobranie
    "honey_harvest",
    "honey_frames_returned",
    # matka i rój
    "queen_introduced",
    "queen_removed",
    "queen_cell_added",
    "queen_cells_removed",
    "swarm_caught",
    "split_made",
    # leczenie
    "treatment_oxalic_acid",
    "treatment_formic_acid",
    "treatment_apistan",
    "treatment_apivar",
    "treatment_other_varroa",
    "treatment_nosema",
    "treatment_other",
    # ul i sprzęt
    "hive_cleaned",
    "hive_moved",
    "entrance_reduced",
    "entrance_opened",
    "mouse_guard_added",
    "mouse_guard_removed",
    "insulation_added",
    "insulation_removed",
    "other",  # inne → action_other
]

ACTION_LABELS = {
    "feeding_syrup": "dokarmianie syropem cukrowym",
    "feeding_candy": "dokarmianie ciastem/kandem",
    "feeding_pollen": "podanie substytutu pyłku",
    "feeding_water": "uzupełnienie pojenia",
    "comb_added_drawn": "dodanie ramki z suszem",
    "comb_added_foundation": "dodanie ramki z węzą",
    "comb_removed_old": "wyjęcie starego/czarnego plastra",
    "comb_removed_drone": "wyjęcie plastra z czerwiem trutowym",
    "uncapping": "odsklepienie zapasów",
    "super_added": "dodanie nadstawki miodnej",
    "super_removed": "zdjęcie nadstawki",
    "division_board_moved": "przesunięcie deski działowej",
    "hive_expanded": "rozszerzenie gniazda",
    "honey_harvest": "miodobranie (wyjęcie ramek)",
    "honey_frames_returned": "zwrot odwirowanych ramek",
    "queen_introduced": "wprowadzenie nowej matki",
    "queen_removed": "usunięcie matki",
    "queen_cell_added": "dodanie matecznika",
    "queen_cells_removed": "usunięcie mateczników rojowych",
    "swarm_caught": "złapanie i osadzenie roju",
    "split_made": "zrobienie odkładu",
    "treatment_oxalic_acid": "leczenie kwasem szczawiowym (Varroa)",
    "treatment_formic_acid": "leczenie kwasem mrówkowym (Varroa)",
    "treatment_apistan": "paski Apistan/Bayvarol",
    "treatment_apivar": "paski Apivar",
    "treatment_other_varroa": "inne leczenie Varroa",
    "treatment_nosema": "leczenie Nosema",
    "treatment_other": "inne leczenie",
    "hive_cleaned": "czyszczenie dennicy",
    "hive_moved": "przeniesienie ula",
    "entrance_reduced": "zwężenie wylotka",
    "entrance_opened": "powiększenie wylotka",
    "mouse_guard_added": "założenie kratki myszowej",
    "mouse_guard_removed": "zdjęcie kratki myszowej",
    "insulation_added": "dołożenie ocieplenia",
    "insulation_removed": "zdjęcie ocieplenia",
    "other": "inne",
}
