# Opisy kodów pogody WMO (po polsku) — https://open-meteo.com/en/docs
WEATHER_CODES = {
    0: "Bezchmurnie",
    1: "Przeważnie bezchmurnie",
    2: "Częściowe zachmurzenie",
    3: "Zachmurzenie całkowite",
    45: "Mgła",
    48: "Mgła osadzająca szadź",
    51: "Mżawka słaba",
    53: "Mżawka umiarkowana",
    55: "Mżawka gęsta",
    56: "Marznąca mżawka słaba",
    57: "Marznąca mżawka gęsta",
    61: "Deszcz słaby",
    63: "Deszcz umiarkowany",
    65: "Deszcz silny",
    66: "Marznący deszcz słaby",
    67: "Marznący deszcz silny",
    71: "Śnieg słaby",
    73: "Śnieg umiarkowany",
    75: "Śnieg silny",
    77: "Ziarna śniegu",
    80: "Przelotny deszcz słaby",
    81: "Przelotny deszcz umiarkowany",
    82: "Przelotny deszcz silny",
    85: "Przelotny śnieg słaby",
    86: "Przelotny śnieg silny",
    95: "Burza",
    96: "Burza z gradem",
    99: "Burza z silnym gradem",
}
